server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangtaobest1/jMing.git #配置git仓库地址
          searchPaths: 稻草人 #配置仓库路径
          username: *  #访问git仓库的用户名
          password: * #访问git仓库的用户密码
      label: master #配置仓库的分支
  rabbitmq:
    host: 47.98.58.255
    port: 5672
    username: mqcs
    password: 123456
    virtualHost: /
    publisherConfirms: true
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1 # 从队列每次取一个
        auto-startup: true
        default-requeue-rejected: true # 失败后重试
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

